require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@4.3.0_@capacitor+core@4.3.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@4.3.0_@capacitor+core@4.3.0/node_modules/@capacitor/ios'
  pod 'CapacitorCommunityMedia', :path => '../../node_modules/.pnpm/@capacitor-community+media@4.0.0-0_@capacitor+core@4.3.0/node_modules/@capacitor-community/media'
  pod 'CapacitorCamera', :path => '../../node_modules/.pnpm/@capacitor+camera@4.1.2_@capacitor+core@4.3.0/node_modules/@capacitor/camera'
  pod 'CapacitorFilesystem', :path => '../../node_modules/.pnpm/@capacitor+filesystem@4.1.2_@capacitor+core@4.3.0/node_modules/@capacitor/filesystem'
  pod 'CapawesomeCapacitorFilePicker', :path => '../../node_modules/.pnpm/@capawesome+capacitor-file-picker@0.5.1_@capacitor+core@4.3.0/node_modules/@capawesome/capacitor-file-picker'
  pod 'Jonz94CapacitorImagePicker', :path => '../../../capacitor-image-picker'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'YPImagePicker', :git => 'https://github.com/jonz94/YPImagePicker.git', :tag => '5.2.1.0'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
